name: user_data
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.7.0-267.0.dev

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  api:
    path: ../api

dev_dependencies:
  graphql_codegen: ^1.1.1
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
